Add function to change I2C address of TMF8801
107-systems/107-Arduino-TMF8801 pull request #42
Opened 2022-01-06 11:53 UTC by generationmake

Add function to change I2C address of TMF8801

Attention: does not work with TMF8801 out of the box. You first have to update the RAM firmware of TMF8801 as described in the datasheet.

2022-01-06 20:58 UTC, aentinger requested changes
Phew, the PRs get more and more (and are partially overlapping). I think you should straighten them out a bit. Alternately I might be able to straighten them out by the end of next week (I hope).

2022-01-06 20:58 UTC, aentinger commented on src/107-Arduino-TMF8801.cpp
> +  _gpio_control=0x00;
Thank you for putting the initialisation into the Ctor. If you put it now up a couple of lines (either before or after the existing initialisations of e.g. _calib_data) I shall be most grateful :wink:

2022-01-06 20:58 UTC, aentinger commented on src/107-Arduino-TMF8801.cpp
> +  }
```suggestion
  return true;
  }
```

2022-01-06 20:58 UTC, aentinger commented on src/107-Arduino-TMF8801.cpp
>    return true;
```suggestion
  return false;
```

2022-01-06 20:58 UTC, aentinger commented on src/107-Arduino-TMF8801.cpp
> +uint32_t ArduinoTMF8801::read_serial_number(void)
```suggestion
uint32_t ArduinoTMF8801::read_serial_number()
```
Writing `void` is superfluous in C++.

2022-01-06 20:58 UTC, aentinger commented on src/107-Arduino-TMF8801.cpp
> +  Serial.print("STATUS = 0x");
Please no `Serial.print` statements within library functions. You expect such a function to only read and return a serial number, not to print any status on Serial.

2022-01-06 20:58 UTC, aentinger commented on src/107-Arduino-TMF8801.h
> +  uint32_t read_serial_number(void);
```suggestion
  uint32_t read_serial_number();
```

2022-01-06 20:58 UTC, aentinger commented on src/107-Arduino-TMF8801.h
> +  void change_i2c_address(uint8_t new_address);
```suggestion
  void change_i2c_address(uint8_t const new_address);
```
Const-correctness 4tw ;) Also change in function definition.

2022-01-06 20:58 UTC, aentinger commented on src/TMF8801/TMF8801_Api.h
> +  void application_read_serial_number(uint32_t const & serial_number);
Why `const &`? Does this even work? I suggest the following signature ...
```suggestion
  uint32_t application_read_serial_number();
```

2022-01-07 01:04 UTC, generationmake commented
Hi @aentinger 
Sorry for the confusion ..
All my PRs build on top of each other, so I suggest to work on and merge one after another.
So please let's start with PR #40 
For now I am done with my addition to the code. So no more PRs for now ;-)

2022-01-07 13:59 UTC, aentinger approved these changes
LGTM :+1: Though untangling all that stuff required some major git-fu.

2022-01-07 14:00 UTC, merged

2022-01-07 16:32 UTC, generationmake commented
Hi @aentinger 
Thanks for merging all the PRs although it was a mess.
I reviewed your changes and they seem to be reasonable.
Thank you